name: KaiHeiLa.Net Deploy

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  deploy:
    
    # Build Solution
    
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x

    - name: Restore Dependencies
      run: dotnet restore src

    - name: Build
      run: dotnet build src --no-restore

    - name: Test
      run: dotnet test src --no-build --verbosity normal
      env:
        KAIHEILA_NET_TEST_TOKEN: ${{ secrets.KAIHEILA_NET_TEST_TOKEN }}

    # Packages

    - name: Generate Packages
      run: dotnet pack src --configuration Release --output packages
      
    - name: Push Packages to NuGet
      run: dotnet nuget push ./packages/*.nupkg -k ${NUGET_TOKEN} -s https://api.nuget.org/v3/index.json --skip-duplicate
      env:
        NUGET_TOKEN: ${{secrets.NUGET_API_KEY}}

    - name: Push Packages to Github
      run: dotnet nuget push ./packages/*.nupkg -k ${GITHUB_TOKEN} -s https://nuget.pkg.github.com/gehongyan/index.json --skip-duplicate
      env:
        GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}

    # DocFX
    
    - uses: nikeee/docfx-action@v1.0.0
      name: Build Doc
      with:
        args: ./docs/docfx.json

    - uses: finnp/create-file-action@master
      name: Add CNAME
      env:
        FILE_NAME: "docs/_site/CNAME"
        FILE_DATA: "kaiheila.net"

    - name: Publish Doc
      uses: cpina/github-action-push-to-another-repository@main
      env:
        API_TOKEN_GITHUB: ${{ secrets.ACTIONS_DEPLOY_KEY }}
      with:
        source-directory: docs/_site/
        destination-github-username: gehongyan
        destination-repository-username: gehongyan
        destination-repository-name: KaiHeiLa.Net.Doc
        target-directory: docs
        user-email: gehongyan1996@126.com
