name: Kook.Net Documentation

on:
  workflow_call:
    secrets:
      DOC_DEPLOY_KEY:
        description: 'NuGet API Key'
        required: true

jobs:
  doc:
    name: Publish Documentation
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          global-json-file: global.json

      - name: Cache Dependencies
        uses: actions/cache@v4
        with:
          path: ~/.nuget/packages
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/*.csproj', 'Kook.Net.targets') }}
          restore-keys: |
            ${{ runner.os }}-nuget

      - name: Setup DocFX
        run: dotnet tool install -g docfx

      - name: Build docs
        run: docfx docs/docfx.json

      - uses: finnp/create-file-action@master
        name: Add CNAME
        env:
          FILE_NAME: "docs/_site/CNAME"
          FILE_DATA: "kooknet.dev"

      - name: Publish Doc
        uses: cpina/github-action-push-to-another-repository@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.DOC_DEPLOY_KEY }}
        with:
          source-directory: docs/_site/
          destination-github-username: gehongyan
          destination-repository-username: gehongyan
          destination-repository-name: Kook.Net.Doc
          target-directory: docs
          user-email: gehongyan1996@126.com
