name: Kook.Net on Release

on:
  push:
    branches: [ doc ]
  pull_request:
    branches: [ doc ]
  release:
    types: [ published ]

jobs:
  build_and_test:
    name: Build and Test
    strategy:
      matrix:
        target: [ windows-latest, ubuntu-latest, macOS-latest ]
    uses: ./.github/workflows/build-test.yml
    with:
      target: ${{ matrix.target }}
      dotnet-version: 10.0.x

  publish_test_results:
    name: Publish Test Results
    needs: build_and_test
    uses: ./.github/workflows/publish-test-results.yml

  call_doc:
    name: Generate Documentation
    needs: build_and_test
    uses: ./.github/workflows/doc.yml
    with:
      dotnet-version: 10.0.x
    secrets:
      DOC_DEPLOY_KEY: ${{ secrets.ACTIONS_DEPLOY_KEY }}
